// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/(something).tsx";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/_404.tsx";
import * as $3 from "./routes/_app.tsx";
import * as $4 from "./routes/_layout.tsx";
import * as $5 from "./routes/_middleware.ts";
import * as $6 from "./routes/api/_middleware.ts";
import * as $7 from "./routes/api/joke.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/myHandler.tsx";
import * as $$0 from "./islands/InstallPWAButton.tsx";

const manifest = {
  routes: {
    "./routes/(something).tsx": $0,
    "./routes/[name].tsx": $1,
    "./routes/_404.tsx": $2,
    "./routes/_app.tsx": $3,
    "./routes/_layout.tsx": $4,
    "./routes/_middleware.ts": $5,
    "./routes/api/_middleware.ts": $6,
    "./routes/api/joke.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/myHandler.tsx": $9,
  },
  islands: {
    "./islands/InstallPWAButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
